name: Build docker

on:
  push:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - id: commit
        uses: prompt/actions-commit-hash@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      -
        name: Build and push on master
        uses: docker/build-push-action@v6
        if: github.ref == 'refs/heads/master'
        with:
          push: true
          tags: |
            iantorres/service-bench:latest
      -
        name: Build and push on commit
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            iantorres/service-bench:${{ steps.commit.outputs.short }}
